class AppConstants {
  static const List<Map<String, String>> indianLanguages = [
    {'code': 'en', 'name': 'English', 'flag': '🇬🇧'},
    {'code': 'hi', 'name': 'Hindi', 'flag': '🇮🇳'},
    {'code': 'bn', 'name': 'Bengali', 'flag': '🇮🇳'},
    {'code': 'ta', 'name': 'Tamil', 'flag': '🇮🇳'},
    {'code': 'te', 'name': 'Telugu', 'flag': '🇮🇳'},
    {'code': 'mr', 'name': 'Marathi', 'flag': '🇮🇳'},
    {'code': 'gu', 'name': 'Gujarati', 'flag': '🇮🇳'},
    {'code': 'kn', 'name': 'Kannada', 'flag': '🇮🇳'},
    {'code': 'ml', 'name': 'Malayalam', 'flag': '🇮🇳'},
    {'code': 'pa', 'name': 'Punjabi', 'flag': '🇮🇳'},
    {'code': 'or', 'name': 'Odia', 'flag': '🇮🇳'},
    {'code': 'as', 'name': 'Assamese', 'flag': '🇮🇳'},
    {'code': 'ur', 'name': 'Urdu', 'flag': '🇮🇳'},
    {'code': 'sa', 'name': 'Sanskrit', 'flag': '🇮🇳'},
    {'code': 'ne', 'name': 'Nepali', 'flag': '🇮🇳'},
    {'code': 'sd', 'name': 'Sindhi', 'flag': '🇮🇳'},
    {'code': 'kok', 'name': 'Konkani', 'flag': '🇮🇳'},
    {'code': 'mai', 'name': 'Maithili', 'flag': '🇮🇳'},
    {'code': 'bho', 'name': 'Bhojpuri', 'flag': '🇮🇳'},
    {'code': 'doi', 'name': 'Dogri', 'flag': '🇮🇳'},
    {'code': 'sat', 'name': 'Santali', 'flag': '🇮🇳'},
    {'code': 'mni', 'name': 'Manipuri', 'flag': '🇮🇳'},
  ];

  static const Map<String, String> languageToTtsLocale = {
    'en': 'en-US',
    'hi': 'hi-IN',
    'bn': 'bn-IN',
    'ta': 'ta-IN',
    'te': 'te-IN',
    'mr': 'mr-IN',
    'gu': 'gu-IN',
    'kn': 'kn-IN',
    'ml': 'ml-IN',
    'pa': 'pa-IN',
    'or': 'or-IN',
    'as': 'as-IN',
    'ur': 'ur-IN',
    'sa': 'sa-IN',
    'ne': 'ne-NP',
    'sd': 'sd-IN',
    'kok': 'kok-IN',
    'mai': 'mai-IN',
    'bho': 'bho-IN',
    'doi': 'doi-IN',
    'sat': 'sat-IN',
    'mni': 'mni-IN',
  };

  static const Map<String, String> languageToSpeechLocale = {
    'en': 'en_US',
    'hi': 'hi_IN',
    'bn': 'bn_IN',
    'ta': 'ta_IN',
    'te': 'te_IN',
    'mr': 'mr_IN',
    'gu': 'gu_IN',
    'kn': 'kn_IN',
    'ml': 'ml_IN',
    'pa': 'pa_IN',
    'or': 'or_IN',
    'as': 'as_IN',
    'ur': 'ur_IN',
    'sa': 'sa_IN',
    'ne': 'ne_NP',
    'sd': 'sd_IN',
    'kok': 'kok_IN',
    'mai': 'mai_IN',
    'bho': 'bho_IN',
    'doi': 'doi_IN',
    'sat': 'sat_IN',
    'mni': 'mni_IN',
  };
}